version: '3'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "project"
      MYSQL_USER: "rohit"
      MYSQL_PASSWORD: "sagar"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations todos &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn todoApp.wsgi:application -b 0.0.0.0:8000 -w 3"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 3306
      DJANGO_DB_NAME: project
      DJANGO_DB_USER: rohit
      DJANGO_DB_PASSWORD: sagar

volumes:
  mysql_data:
